import type { Metadata } from "next";
import Header from "@/components/header/header";
import QueryProvider from "@/components/query-provider/query-provider";
import './globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className="min-h-full flex flex-col">
          <Header />
          {children}
        </body>
      </QueryProvider>
    </html>
  );
}
